openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Sheet SKU API
  description: >
    Returns the SKU from row 2 (A2) of the bound Google Sheet.
  license:
    name: MIT

# Use the deployed Web App URL that ends with /exec
servers:
  - url: https://script.google.com/macros/s/AKfycby17EPB-TZghKISHlmOC8cfbghlQx3PkFuY6ZexkDYcjd06AS2WFsMUZYDeYVZbPWuLGA/exec

paths:
  /:
    get:
      summary: Get SKU from row 2 (A2)
      operationId: getSkuFromA2
      responses:
        '200':
          description: SKU returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  sku:
                    type: string
                    example: "123"
              examples:
                success:
                  value:
                    ok: true
                    sku: "123"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Sheet not found"

