openapi: "3.0.0"
info:
  version: 1.0.0
  title: BCS Order Arrival Lookup
  description: >
    Retrieve the arrival_date for a single order_id (exact match) from Google Sheets.
  license:
    name: MIT

# IMPORTANT: Use your full Web App URL that already ends with /exec
servers:
  - url: https://script.google.com/macros/s/AKfycbwkAc3CUrPfX6OdLrWQ8lFWV9QckACsipt51zO9nbiYb2PgRH-1d2NvS4NlOL13LYEB7Q
paths:
  /:
    post:
      summary: Get arrival date for a single order_id (exact match)
      operationId: getArrivalDateByOrderId
      parameters:
        - in: query
          name: order_id
          schema:
            type: string
            minLength: 1
            pattern: '^[^\n\r,]+$'   # disallow commas/newlines (single ID only)
          required: true
          description: The exact order_id to look up.
      responses:
        '200':
          description: Lookup result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: True if an exact match was found.
                  order_id:
                    type: string
                    description: Echo of the requested order_id.
                  arrival_date:
                    type: string
                    format: date
                    description: Arrival date in YYYY-MM-DD if found.
                  error:
                    type: string
                    description: Error message when ok=false.
                required:
                  - ok
              examples:
                found:
                  summary: Successful match
                  value:
                    ok: true
                    order_id: "T10293"
                    arrival_date: "2025-12-03"
                not_found:
                  summary: No match
                  value:
                    ok: false
                    order_id: "T99999"
                    error: "Order not found"
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Missing required parameter: order_id"
