openapi: "3.0.0"
info:
  version: 1.0.1
  title: Google Sheet Query API
  description: >
    This API retrieves product information from a Google Sheet based on SKU values.
  license:
    name: MIT
servers:
  - url: https://script.google.com/macros/s/AKfycbwhb_t3eaMiNABOyec9v8P8lud6TdgTBwKtEgdgtJD_XUEuAM33n4ChzTpxPwFj8y_4Gg
paths:
  /exec:
    get:
      summary: Retrieve product details by SKU
      operationId: getProductsBySKU
      parameters:
        - in: query
          name: SKU
          schema:
            type: string
            minLength: 1
          required: true
          description: SKU value to search for. Performs a partial match on the SKU column.
      responses:
        '200':
          description: Products found matching the SKU
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of rows matching the SKU
                  entries:
                    type: array
                    description: List of matching products
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "1003"
                        name:
                          type: string
                          example: "Product 3"
                        description:
                          type: string
                          example: "A product"
        '400':
          description: Missing or invalid SKU parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Missing SKU parameter
